steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ds-domestock/domestock:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ds-domestock/domestock:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'domestock',
      '--image',
      'gcr.io/ds-domestock/domestock:$COMMIT_SHA',
      '--region',
      'us-central1',
      '--allow-unauthenticated',
      '--set-env-vars', 'APP_NAME=${_APP_NAME}',
      '--set-env-vars', 'APP_ENV=local',
      '--set-env-vars', 'APP_KEY=${_APP_KEY}',
      '--set-env-vars', 'APP_DEBUG=${_APP_DEBUG}',
      '--set-env-vars', 'APP_TIMEZONE=${_APP_TIMEZONE}',
      '--set-env-vars', 'APP_URL=${_APP_URL}',
      '--set-env-vars', 'APP_LOCALE=${_APP_LOCALE}',
      '--set-env-vars', 'APP_FALLBACK_LOCALE=${_APP_FALLBACK_LOCALE}',
      '--set-env-vars', 'APP_FAKER_LOCALE=${_APP_FAKER_LOCALE}',
      '--set-env-vars', 'APP_MAINTENANCE_DRIVER=${_APP_MAINTENANCE_DRIVER}',
      '--set-env-vars', 'BCRYPT_ROUNDS=${_BCRYPT_ROUNDS}',
      '--set-env-vars', 'LOG_CHANNEL=stderr',
      '--set-env-vars', 'LOG_STACK=${_LOG_STACK}',
      '--set-env-vars', 'LOG_DEPRECATIONS_CHANNEL=${_LOG_DEPRECATIONS_CHANNEL}',
      '--set-env-vars', 'LOG_LEVEL=${_LOG_LEVEL}',
      '--set-env-vars', 'DB_CONNECTION=${_DB_CONNECTION}',
      '--set-env-vars', 'DB_HOST=${_DB_HOST}',
      '--set-env-vars', 'DB_PORT=${_DB_PORT}',
      '--set-env-vars', 'DB_DATABASE=${_DB_DATABASE}',
      '--set-env-vars', 'DB_USERNAME=${_DB_USERNAME}',
      '--set-env-vars', 'DB_PASSWORD=${_DB_PASSWORD}',
      '--set-env-vars', 'APP_STORAGE=${_APP_STORAGE}',
      '--set-env-vars', 'VIEW_COMPILED_PATH=${_VIEW_COMPILED_PATH}',
      '--set-env-vars', 'APP_SERVICES_CACHE=${_APP_SERVICES_CACHE}',
      '--set-env-vars', 'APP_PACKAGES_CACHE=${_APP_PACKAGES_CACHE}',
      '--set-env-vars', 'APP_CONFIG_CACHE=${_APP_CONFIG_CACHE}',
      '--set-env-vars', 'APP_ROUTES_CACHE=${_APP_ROUTES_CACHE}',
    ]
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - gcr.io/ds-domestock/domestock:$COMMIT_SHA
