steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ds-domestock/domestock:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ds-domestock/domestock:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'default',
      '--image',
      'gcr.io/ds-domestock/domestock:$COMMIT_SHA',
      '--region',
      'us-central1',
      '--allow-unauthenticated'
    ]
    env:
      - 'APP_NAME=${_APP_NAME}'
      - 'APP_ENV=${_APP_ENV}'
      - 'APP_KEY=${_APP_KEY}'
      - 'APP_DEBUG=${_APP_DEBUG}'
      - 'APP_TIMEZONE=${_APP_TIMEZONE}'
      - 'APP_URL=${_APP_URL}'
      - 'APP_LOCALE=${_APP_LOCALE}'
      - 'APP_FALLBACK_LOCALE=${_APP_FALLBACK_LOCALE}'
      - 'APP_FAKER_LOCALE=${_APP_FAKER_LOCALE}'
      - 'APP_MAINTENANCE_DRIVER=${_APP_MAINTENANCE_DRIVER}'
      - 'BCRYPT_ROUNDS=${_BCRYPT_ROUNDS}'
      - 'LOG_CHANNEL=${_LOG_CHANNEL}'
      - 'LOG_STACK=${_LOG_STACK}'
      - 'LOG_DEPRECATIONS_CHANNEL=${_LOG_DEPRECATIONS_CHANNEL}'
      - 'LOG_LEVEL=${_LOG_LEVEL}'
      - 'DB_CONNECTION=${_DB_CONNECTION}'
      - 'DB_HOST=${_DB_HOST}'
      - 'DB_PORT=${_DB_PORT}'
      - 'DB_DATABASE=${_DB_DATABASE}'
      - 'DB_USERNAME=${_DB_USERNAME}'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - 'APP_STORAGE=${_APP_STORAGE}'
      - 'VIEW_COMPILED_PATH=${_VIEW_COMPILED_PATH}'
      - 'APP_SERVICES_CACHE=${_APP_SERVICES_CACHE}'
      - 'APP_PACKAGES_CACHE=${_APP_PACKAGES_CACHE}'
      - 'APP_CONFIG_CACHE=${_APP_CONFIG_CACHE}'
      - 'APP_ROUTES_CACHE=${_APP_ROUTES_CACHE}'
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - gcr.io/ds-domestock/domestock:$COMMIT_SHA
